# Generated by Django 5.0.6 on 2024-09-12 16:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('r', 'Ready'), ('nr', 'NotReady'), ('o', 'Old')], default='nr', max_length=2)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('teamaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamaker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
