# Generated by Django 5.0.6 on 2024-09-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_rename_drinks_drink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='name',
            new_name='title',
        ),
    ]
